### ISSUE TITLE
Doesn't work.

### ISSUE THREAD

**Issue by Akicita33** [teelolws/UnderlightAnglerAuto#2]
Supposedly it should change me to fish when I go into water. This doesn't happen. 

Yes, UA is equipped in fishing equipment slot. 
No, I'm not in combat.
Yes I have bag slots open.

**Comment by teelolws** [comment]
First, have you updated the addon since 10.0.5? There was a change on Blizzards end that broke this addon, but I have since fixed it.

Next, aside from interference from another addon, there is one other thing that can stop it from working. In Valdrakken, talk to this NPC:
![image](https://user-images.githubusercontent.com/49792789/219901713-92c62693-6def-445b-88e9-ee8c34f03a93.png)
![image](https://user-images.githubusercontent.com/49792789/219901720-c853e19b-0e42-4de9-973b-e2a9b4c05a90.png)

It needs to be set to always show your fishing rod, not just while you're fishing. Unfortunately, that NPC blocks the Underlight Angler abilities, too.

**Comment by Akicita33** [comment]
I installed it today.
